from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
import io

def generate_itinerary_pdf(destination_city, total_budget):
    # Bellekte sanal bir PDF dosyası oluşturuyoruz (Streamlit'ten indirmek için)
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # 1. Arka Plan Fotoğrafı (API'den rastgele bulanık manzara)
    image_url = "https://picsum.photos/800/1200?blur=2" 
    try:
        img = ImageReader(image_url)
        c.drawImage(img, 0, 0, width=width, height=height)
    except:
        # Fotoğraf çekilemezse yedek koyu lacivert arka plan
        c.setFillColorRGB(0.1, 0.15, 0.3)
        c.rect(0, 0, width, height, fill=1, stroke=0)

    # 2. Yazıların Okunabilirliği İçin Alt Kısma Koyu Bir Bant Çizelim
    c.setFillColorRGB(0, 0, 0)
    c.rect(0, 0, width, 250, fill=1, stroke=0) # Alttan 250 piksel yüksekliğinde siyah bant

    # 3. Ana Başlık (Tipografi)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 42)
    c.drawString(40, 180, "GLOBAL TRAVEL")
    c.drawString(40, 135, "BOOKLET")
    
    # 4. Dinamik Şehir Adı ve Bütçe
    c.setFont("Helvetica", 18)
    c.setFillColor(colors.orange)
    c.drawString(40, 95, f"Exclusive Route to: {destination_city.upper()}")
    
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.lightgrey)
    c.drawString(40, 65, f"Estimated Budget: {total_budget} EUR")
    
    # 5. Alt Kısım Branding
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.gray)
    c.drawString(40, 30, "Autonomously Generated by Global Route Planner V2")
    
    c.showPage()
    c.save()
    
    buffer.seek(0)
    return buffer
