from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os

def create_cover_page(c, destination_city, total_budget):
    width, height = A4
    
    # 1. Tam Sayfa Arka Plan (Örn: Zarif bir Koyu Lacivert)
    c.setFillColorRGB(0.1, 0.15, 0.3)  # Koyu Lacivert tonu
    c.rect(0, 0, width, height, fill=1, stroke=0)
    
    # 2. Ana Başlık (Tipografi)
    c.setFillColor(colors.whitesmoke)
    c.setFont("Helvetica-Bold", 42)
    c.drawString(50, height - 200, "GLOBAL TRAVEL")
    c.drawString(50, height - 250, "BOOKLET")
    
    # 3. Dinamik Alt Başlık (Data Merge)
    c.setFont("Helvetica", 20)
    c.setFillColor(colors.orange)
    c.drawString(50, height - 320, f"Exclusive Route to: {destination_city.upper()}")
    
    # 4. Estetik Çizgi ve Bütçe Özeti
    c.setStrokeColor(colors.orange)
    c.setLineWidth(2)
    c.line(50, height - 350, 250, height - 350)
    
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.whitesmoke)
    c.drawString(50, height - 380, f"Estimated Budget: {total_budget} EUR")
    
    # 5. Alt Kısım (Branding)
    c.setFont("Helvetica-Oblique", 12)
    c.drawString(50, 50, "Autonomously Generated by Global Route Planner V2")
    
    c.showPage() # Kapağı bitir ve yeni sayfaya geç

# Test için PDF'i oluşturma
c = canvas.Canvas("Premium_Route.pdf", pagesize=A4)
create_cover_page(c, "Amsterdam & Bruges", "3885.45")
c.save()